name: daily_fetch
on:
  schedule:
    - cron: '0 12 * * *'
jobs:
  fetch-and-generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: pip install openai requests python-dateutil pyyaml

      - name: Fetch latest JP article
        env:
          WP_API: https://studyriver.jp/wp-json/wp/v2/posts?per_page=1
        run: python scripts/fetch_latest.py  # -> tmp/article.json

      - name: Story L3 → L2/L1
        run: python scripts/story_from_article.py tmp/article.json stories/

      - name: Translate Tier-A langs
        env:
          TRANSLATE_LANGS: ${{ vars.TRANSLATE_LANGS }}
        run: python scripts/translate.py stories/

      - name: Commit
        run: |
          git config user.name "gpbot"
          git config user.email "gpbot@example.com"
          git add stories
          git commit -m "Daily stories $(date -u '+%Y-%m-%d')" || echo "No changes"
          git push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
