name: daily_fetch
on:
  schedule:
    - cron: '0 12 * * *'
jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install -r requirements.txt
      - run: python scripts/fetch_studyriver.py
      - run: python scripts/generate_story.py --level l3 --json-latest
      - run: python scripts/translate.py --from l3 --to l2,l1
      - uses: EndBug/add-and-commit@v9
        with:
          message: 'daily fetch ${{ github.run_id }}'
