name: daily_fetch
on:
  schedule:
    # 毎日 07:00 JST 実行
    - cron: '0 22 * * *'

  # 手動トリガーも残す
  workflow_dispatch:
  
jobs:
  fetch-and-generate:
    runs-on: ubuntu-latest

    # ── 1) 全ステップ共通の環境変数 ─────────────────────────────
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      TRANSLATE_LANGS: ${{ vars.TRANSLATE_LANGS }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # ── 2) 依存ライブラリ ─────────────
      - name: Install deps
        run: |
          pip install \
            openai requests python-dateutil regex

      # ── 3) Fetch 最新 JP 記事 → tmp_article.json ───────────────
      - name: Fetch latest JP article
        run: python scripts/fetch_latest.py

      # ── 4) 物語生成 (L3→L2→L1) ────────────────────────────────
      - name: Story L3 → L2/L1
        run: python scripts/story_from_article.py

      # ── 5) 多言語翻訳 ───────────────────────────────────────
      - name: Translate Core-6 languages
        run: python scripts/translate.py

      # （post-process で jaconv 等を使う場合は↑depsに追加して
      #   ここにステップを挟む）

      # ── 6) Commit & Push ────────────────────────────────────
      - name: Commit
        run: |
          git config user.name "gpbot"
          git config user.email "gpbot@example.com"
          git add stories
          git commit -m "Daily stories $(date -u '+%Y-%m-%d')" || echo "No changes"
          git push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
