name: monthly_epub
on:
  # 毎月 1日・15日 の 00:00 UTC（＝JST 09:00）
  schedule:
    - cron: '0 0 1 * *'   # JST 09:00 毎月1日
    # - cron: '0 0 15 * *'  # JST 09:00 毎月15日 8/2以降に対応
  workflow_dispatch:

jobs:
  build-epub:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # ── 依存 ───────────────────────────────
      - name: Install deps
        run: |
          pip install ebooklib markdown python-dateutil regex jaconv

      # ── 前月分 EPUB を束ねる ────────────────
      - name: Compile last-month EPUBs
        env:
          TARGET_COUNT: ${{ vars.TARGET_COUNT }}
        run: python scripts/compile_epubs.py

      # ──（あとで SFTP に置き換え）───────────
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: epub-bundle
          path: dist/
