name: monthly_epub
on:
  schedule:
    - cron: '0 0 1 * *'
jobs:
  build-epub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Install deps
        run: pip install openai ebooklib markdown python-dateutil

      - name: Compile last-month EPubs
        env:
          TARGET_COUNT: ${{ vars.TARGET_COUNT }}
        run: python scripts/compile_epubs.py stories/ dist/

      # ↓⑥を実装する時はここで gplaybooks へ SFTP
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: epub-bundle
          path: dist/
